added hero for tags page
deepgram/web-next pull request #108
Opened 2022-09-01 18:27 UTC by briancbarrow

2022-09-02 09:55 UTC, lukeocodes approved these changes
Added some code suggestions. Main one is removing those commented out console.logs though lol

2022-09-02 09:55 UTC, lukeocodes commented on blog/src/components/authors/Hero.astro
> +// console.log({ svg, title });
```suggestion
```

2022-09-02 09:55 UTC, lukeocodes commented on blog/src/components/tags/Hero.astro
> +// console.log({ svg, title });
```suggestion
```

2022-09-02 09:55 UTC, lukeocodes commented on blog/src/assets/styles/blog.css
> +.bg-svg {
```suggestion
.bg-responsive-svg {
```

2022-09-02 09:55 UTC, lukeocodes commented on blog/src/assets/styles/blog.css
> +	.bg-svg {
```suggestion
	.bg-responsive-svg {
```

2022-09-02 09:55 UTC, lukeocodes commented on blog/src/assets/styles/blog.css
> +	.bg-svg {
```suggestion
	.bg-responsive-svg {
```

2022-09-02 09:55 UTC, lukeocodes commented on blog/src/assets/styles/blog.css
> +	.bg-svg {
```suggestion
	.bg-responsive-svg {
```

2022-09-02 09:55 UTC, lukeocodes commented on blog/src/assets/styles/blog.css
> +	.bg-svg {
```suggestion
	.bg-responsive-svg {
```

2022-09-02 09:55 UTC, lukeocodes commented on blog/src/pages/authors/index.astro
> +	<ContrastSection contrast="darkCharcoal" class="bg-starburst-gradient bg-svg" background="white" bottomDivider="eclipse-divider">
```suggestion
	<ContrastSection contrast="darkCharcoal" class="bg-starburst-gradient bg-responsive-svg" background="white" bottomDivider="eclipse-divider">
```

2022-09-02 09:55 UTC, lukeocodes commented on blog/src/pages/tags/index.astro
> +// console.log({ uniqueTags });
```suggestion
```

2022-09-02 09:55 UTC, lukeocodes commented on blog/src/pages/tags/index.astro
> +});
```suggestion
allPosts.forEach((post) => {
  tags.push(...post.frontmatter.tags)
});

```

2022-09-02 09:55 UTC, lukeocodes commented on blog/src/pages/tags/index.astro
> +const uniqueTags = Array.from(new Set(tags));
```suggestion
tags = [...new Set(tags)];
```

2022-09-02 09:55 UTC, lukeocodes commented on blog/src/pages/tags/index.astro
> +			{uniqueTags.map((tag) => (
```suggestion
			{tags.map((tag) => (
```

2022-09-02 10:02 UTC, lukeocodes requested changes

2022-09-02 10:02 UTC, lukeocodes commented on blog/src/pages/tags/index.astro
> +		</div>
<LinkCardListTitle> will do what you need here, won't it?

2022-09-02 10:02 UTC, lukeocodes commented on blog/src/pages/tags/index.astro
> +	<PrimarySection class="my-16 mx-16 ml-20">
```suggestion
	<PrimarySection class="my-16 mx-16 ml-20">
```

This is what is breaking the responsiveness. PrimarySection is a class that has concrete margins to make sure every part of the content lines up vertically. What is it you're trying to achieve with this horizonal margin?

2022-09-02 10:11 UTC, lukeocodes commented
![image](https://user-images.githubusercontent.com/956290/188117419-9ad3e597-d7d7-4162-a3c1-aed522cd3265.png)

2022-09-02 15:14 UTC, briancbarrow commented on blog/src/pages/tags/index.astro
> +		</div>
I initially tried it but thought it needed a title so I went with something else. I see now that it doesn't need that so I switched it back.

2022-09-02 16:38 UTC, lukeocodes requested changes

2022-09-02 16:38 UTC, lukeocodes commented on blog/src/pages/tags/index.astro
>  <Layout>
Oops i forgot to mention structured data. Please see /pages/tags/[tag]/[...page].astro for the schema.

Or something like this?

```suggestion
// build json schema object
const schema = {
	"@context": "https://schema.org",
	"@type": "BreadcrumbList",
	itemListElement: [
		{
			"@type": "ListItem",
			position: 1,
			name: "Deepgram Home",
			item: "https://deepgram.com",
		},
		{
			"@type": "ListItem",
			position: 2,
			name: "Blog",
			item: Astro.url.origin,
		},
		{
			"@type": "ListItem",
			position: 3,
			name: "Tags",
		},
	],
};
---

<Layout>
	<JsonLD slot="json:ld" {schema} />
```

2022-09-07 12:02 UTC, lukeocodes approved these changes

2022-09-07 12:02 UTC, merged