testing a thumbs function
deepgram/web-next pull request #30
Opened 2022-07-25 20:52 UTC by briancbarrow

2022-07-27 11:57 UTC, lukeocodes requested changes
As discussed, please use Zapier for the integration with hellonext. This is also missing the components from shared, including the forms.

2022-07-27 14:51 UTC, briancbarrow commented
> This is also missing the components from shared, including the forms.

What do you mean by this? This PR is just for the serverless functions. I'll add the UI code in a separate PR.

2022-07-27 16:16 UTC, briancbarrow commented on serverless/netlify/functions/general-zap/index.js
> +const axios = require('axios')
yep

2022-07-28 12:19 UTC, lukeocodes requested changes
One last change. I linted it for you. Can you configure prettier on your IDE so it runs on save? Config is all set up already

2022-07-28 12:19 UTC, lukeocodes commented on serverless/netlify/functions/forms/index.js
> +}
```suggestion
const axios = require("axios");

exports.handler = async function (event, context) {
	const body = JSON.parse(event.body);
	const hookId = body.hookId;
	const url = `${process.env.ZAP_HOOK_URL}${hookId}`;
	const {
		data: { data: streams },
	} = await axios.post(url, event.body);
	return {
		statusCode: 200,
	};
};

```

2022-07-29 10:41 UTC, lukeocodes commented on serverless/netlify/functions/forms/index.js
> +      "access-control-allow-origin": "*",
We may need to update this to our domains when the sites are launched

2022-07-29 23:18 UTC, MichaelJolley approved these changes

2022-07-29 23:18 UTC, merged