Create Blog “identifying-the-best-agent-to-respond-in-your-ivr-system/index”
deepgram/web-next pull request #514
Opened 2022-09-23 18:05 UTC by MichaelJolley

Automatically generated by Netlify CMS

2022-09-23 20:59 UTC, BekahHW requested changes

2022-09-23 20:59 UTC, BekahHW commented on content/blog/posts/identifying-the-best-agent-to-respond-in-your-ivr-system/index.md
> +   response.say(f"This is the Spanish response and {representative} will help you.",
I don't think that 'f' should be there in the response.say

2022-09-23 20:59 UTC, BekahHW commented on content/blog/posts/identifying-the-best-agent-to-respond-in-your-ivr-system/index.md
> +   response.say(f"This is the Spanish response and {representative} will help you.",
Also, maybe remove the period after you. It's probably grammatically correct, but it's distracting with the , after.

2022-09-23 20:59 UTC, BekahHW commented on content/blog/posts/identifying-the-best-agent-to-respond-in-your-ivr-system/index.md
> +   response.say(f"This is the Spanish response and {representative} will help you.",
oh, maybe that f needs to be there.

2022-09-23 20:59 UTC, BekahHW commented on content/blog/posts/identifying-the-best-agent-to-respond-in-your-ivr-system/index.md
> +To run the application, I fired up two terminals simultaneously in Visual Studio Codel, one to run my Flask application and another for ngrok. Both are important, and you’ll need the ngrok url to add
** Visual Studio Code

2022-09-23 21:38 UTC, geekchick commented on content/blog/posts/identifying-the-best-agent-to-respond-in-your-ivr-system/index.md
> +   response.say(f"This is the Spanish response and {representative} will help you.",
Yep, the f needs to be there. It's for string formatting. A weird Python thing lol

2022-09-27 14:24 UTC, BekahHW approved these changes

2022-09-27 17:40 UTC, closed without merging