promos
deepgram/web-next pull request #53
Opened 2022-08-09 00:43 UTC by SandraRodgers

2022-08-14 11:46 UTC, lukeocodes requested changes

2022-08-14 11:46 UTC, lukeocodes commented on shared/src/pages/marketing.astro
> +import eventImg from "../shared/assets/temp_images/apples.png";
I can see why we use images as sources like this, but in reality the entire banner will be a solid background image, not a transparent asset with a background color. I think the background color should just be a fallback until the background image loads.

2022-08-14 11:46 UTC, lukeocodes commented on shared/src/pages/marketing.astro
> +	formText={[{ label: "Work email", placeholder: "you@company.com" }]}
Spot on, great idea for setting this data in the prop.

2022-08-14 11:46 UTC, lukeocodes commented on shared/src/pages/marketing.astro
> +	date="09-10-22"
This might need to be an ISO timestamp. See /content/blog/posts/<any post>/index.md date frontmatter for the format.

2022-08-14 11:46 UTC, lukeocodes commented on shared/src/shared/components/promos/AbstractPromo.astro
> +	{strapline && <h5 class="uppercase">{strapline}</h5>}
I think the strapline (and the human readable date) done pretty much exactly how I would do them at first. 

My only desire is that they're all uniformly spaced (height and spacing). I dunno the best way to achieve that without a bit of fiddling.

You're definitely close!

2022-08-14 15:59 UTC, lukeocodes commented
I exported the BGs with their BG color and added it to the same directory you used.

2022-08-15 16:21 UTC, SandraRodgers commented on shared/src/shared/components/promos/AbstractPromo.astro
> +	{strapline && <h5 class="uppercase">{strapline}</h5>}
The strapline and the humanReadableDate are the same amount of spacing distant to the title because I set `space-y-1` on the div that contains the strapline/title/date. Is there something else that you mean?

The sizing of the text is definitely off since we haven't made global styles for headings yet.

I'm not sure what to do for this to make it look more uniform, except to add styles for heading sizes.

2022-08-17 11:47 UTC, merged