Author hero
deepgram/web-next pull request #65
Opened 2022-08-16 17:53 UTC by briancbarrow

2022-08-16 18:37 UTC, lukeocodes requested changes

2022-08-16 18:37 UTC, lukeocodes commented on blog/src/pages/authors/[slug].astro
> +	<AuthorHero author={author} />
can you check out [blog/src/pages/index.astro on my PR](https://github.com/deepgram/web-next/blob/lo/blog-homepage/blog/src/pages/index.astro) and see how i put the Hero in a ContrastSection, this will do the curve for you

something like...

`<ContrastSection contrast="darkCharcoal" background="white" bottomDivider="eclipse-divider"><AuthorHero author={author} /></ContrastSection>`

don't worry about overlaying the post cards yet. i have an idea for this but get the curve working without

2022-08-16 18:39 UTC, lukeocodes commented on blog/src/pages/authors/[slug].astro
> +	const sortedAuthors = allAuthors.sort((a, b) => a.title.localeCompare(b.title));
TIL: `localeCompare`... never even knew this was a thing

2022-08-16 18:41 UTC, lukeocodes requested changes

2022-08-16 18:41 UTC, lukeocodes commented on blog/src/pages/authors/[slug].astro
> +	const sortedAuthors = allAuthors.sort((a, b) => a.title.localeCompare(b.title));
Check out how we read in the file name [to get the slug for categories in my current PR](https://github.com/deepgram/web-next/blob/lo/blog-homepage/blog/src/pages/categories/%5Bslug%5D.astro#L7-L18) for an idea on how to get the author's slug from their profile's filename

2022-08-16 18:54 UTC, lukeocodes commented
> Check out how we read in the file name [to get the slug for categories in my current PR](https://github.com/deepgram/web-next/blob/lo/blog-homepage/blog/src/pages/categories/%5Bslug%5D.astro#L7-L18) for an idea on how to get the author's slug from their profile's filename

ignore this comment for this card! this will be helpful when we do the author pages themselves though

2022-08-16 19:43 UTC, briancbarrow commented on blog/src/pages/authors/[slug].astro
> +	const sortedAuthors = allAuthors.sort((a, b) => a.title.localeCompare(b.title));
> TIL: localeCompare... never even knew this was a thing
Thank god for Stack Overflow. I learned it yesterday.

2022-08-16 20:38 UTC, briancbarrow commented on blog/src/components/AuthorHero.astro
> +			<h1 class="name">{author.title}</h1>
@lukeocodes I made a comment here but wanted to call attention to it. Can we change this to author.name? I was just following what was in the current json files but I don't think `title` is the correct property name. Before I changed it I wanted to make sure there wasn't something I was missing

2022-08-17 08:14 UTC, lukeocodes commented on blog/src/components/AuthorHero.astro
> +			<h1 class="name">{author.title}</h1>
Yeh good question. Title is a field that Netlify CMS automatically uses to create the filename. While we can tell Netlify CMS to use another field, in my experience this has caused it to become less reliable in relationship linking. If you like, you can change it in another branch after. Let's get these pages stood up first

2022-08-17 08:28 UTC, lukeocodes commented on blog/src/components/AuthorHero.astro
> +						<!-- <img src="/social/linkedin.svg" /> -->
almost certain that this is causing the lint error

2022-08-17 08:51 UTC, lukeocodes approved these changes

2022-08-17 08:51 UTC, merged