add streaming test suite guide
deepgram/web-next pull request #696
Opened 2023-03-10 02:03 UTC by shirgoldbird

2023-03-10 15:47 UTC, SandraRodgers commented on developers/src/pages/documentation/navigation.json
> +            "name": "Get Started With the Streaming Test Suite",
Let's use the gerund "Getting Started...." so that we keep all the guides titles consistent

2023-03-10 17:09 UTC, SandraRodgers commented on developers/src/pages/documentation/guides/streaming-test-suite/index.mdx
> +1. Check out the [streaming test suite](https://github.com/deepgram/streaming-test-suite/) repository
I checked it out, and it has identical instructions for this section. It's not clear what I need to do to get going with the test suite. Do I need to clone the repo and install packages? Maybe a python user would know, but I'm finding this a little vague.

2023-03-10 20:21 UTC, shirgoldbird commented on developers/src/pages/documentation/guides/streaming-test-suite/index.mdx
> +1. Check out the [streaming test suite](https://github.com/deepgram/streaming-test-suite/) repository
Ah, yes! I should say "clone". Will update.

2023-03-10 20:21 UTC, shirgoldbird commented on developers/src/pages/documentation/navigation.json
> +            "name": "Get Started With the Streaming Test Suite",
Updated!

2023-03-10 20:44 UTC, shirgoldbird commented on developers/src/pages/documentation/guides/streaming-test-suite/index.mdx
> +1. Check out the [streaming test suite](https://github.com/deepgram/streaming-test-suite/) repository
@SandraRodgers do you think I should replace the repo's README with a link to this guide once it's out?

2023-03-14 15:58 UTC, SandraRodgers commented on developers/src/pages/documentation/guides/streaming-test-suite/index.mdx
> +2. `pip install requirements.txt`
Is there supposed to be a `requirements.text` file in the test suite project? I cloned the project and ran `pip install requirements.txt` but got this error:

> ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

This may be because I don't understand something about how to get the project going. If so, that information could be helpful. If not, then maybe something is missing from the project?

2023-03-14 17:04 UTC, SandraRodgers commented on developers/src/pages/documentation/guides/streaming-test-suite/index.mdx
> +First, make sure pyaudio and its portaudio dependency are installed, and you have a microphone connected to your computer. Then, run:
Maybe link to pyaudio and portaudio or put those words in bold to highlight them

2023-03-14 17:21 UTC, SandraRodgers commented on developers/src/pages/documentation/guides/streaming-test-suite/index.mdx
> +Now that you've validated you can stream WAV files and URLs to Deepgram, it's time to start the process of integrating your own audio. To do this, we'll start by taking a step back…and removing Deepg
When you say "the process of integrating your own audio", what do you mean by "your own audio"? As someone who has only tried Deepgram with prerecorded files, hosted URLs, and streaming from my microphone, I'm unclear on this. Probably because I'm not an actual customer with my own audio. But I wonder if there's a way to be less vague about what that means.

2023-03-14 17:25 UTC, SandraRodgers commented on developers/src/pages/documentation/guides/streaming-test-suite/index.mdx
> +### Run the Mock Server
You might want to tell them to switch to the `mock-server` branch, since main doesn't include `server.py` and `client.py`

2023-03-14 17:35 UTC, SandraRodgers commented on developers/src/pages/documentation/guides/streaming-test-suite/index.mdx
> +Using the mock server for testing allows you to focus on getting your audio and client code right. Once you're confident that your audio stream is configured correctly and you're streaming the audio
This seems to be the crux of the whole thing - this project allows users to test that they're configuring everything right so they can then move on to do their own unique integrations/work with DG. Do you think it would be helpful to add this concept to your introduction? I didn't understand why you called it a test-suite, but now that I've read this it makes sense why you would, or at least why you use the term 'test'. But you don't emphasize that as its purpose in the intro.

2023-03-14 17:48 UTC, SandraRodgers commented on developers/src/pages/documentation/guides/streaming-test-suite/index.mdx
> +The mock server exposes a similar interface to Deepgram's streaming service. It accepts websocket connections that specify an encoding, sample rate, and number of channels; and it expects a stream of
Re: "All it does is send back messages confirming how much audio data has been received"

Might be helpful to include a screenshot of what this message would look like. Just a suggestion.

2023-03-14 17:58 UTC, SandraRodgers commented on developers/src/pages/documentation/guides/streaming-test-suite/index.mdx
> +Once you verify your audio is correct, you can try streaming that audio to Deepgram. To do so, simply swap the websocket URL in `client.py` to point to Deepgram—the correct URL is left in a comment f
It might be overkill, but you could include a screenshot of these lines in the code where the comment is so they can visualize what you mean. It would make it very clear that they need to look for a guiding comment in the code.

2023-03-14 18:05 UTC, SandraRodgers commented on developers/src/pages/documentation/guides/streaming-test-suite/index.mdx
> +If you're looking to get started with Deepgram's audio streaming capabilities, our streaming test suite is the perfect place to begin. The test suite provides sample code that allows you to easily st
I think the wording "custom integrations" is misleading. It makes me think they are building integrations with Deepgram that use things like Twilio or other third party technology. It doesn't convey the idea that this will help users to be able to use Deepgram for their own unique use cases, which is what I think you mean.

2023-03-14 18:15 UTC, SandraRodgers requested changes
Made a few suggestions that I hope are helpful

2023-03-14 21:05 UTC, shirgoldbird commented on developers/src/pages/documentation/guides/streaming-test-suite/index.mdx
> +2. `pip install requirements.txt`
Updated!

2023-03-14 21:06 UTC, shirgoldbird commented on developers/src/pages/documentation/guides/streaming-test-suite/index.mdx
> +### Run the Mock Server
I'll get this branch merged into `main` before releasing here 🙏🏻

2023-03-14 21:08 UTC, shirgoldbird commented on developers/src/pages/documentation/guides/streaming-test-suite/index.mdx
> +1. Check out the [streaming test suite](https://github.com/deepgram/streaming-test-suite/) repository
Discussed in call, will add link to repo README but not remove it

2023-03-14 21:14 UTC, shirgoldbird commented on developers/src/pages/documentation/guides/streaming-test-suite/index.mdx
> +Using the mock server for testing allows you to focus on getting your audio and client code right. Once you're confident that your audio stream is configured correctly and you're streaming the audio
Added this to intro!

2023-03-21 17:14 UTC, shirgoldbird commented on developers/src/pages/documentation/guides/streaming-test-suite/index.mdx
> +If you're looking to get started with Deepgram's audio streaming capabilities, our streaming test suite is the perfect place to begin. The test suite provides sample code that allows you to easily st
I've updated this to say "your unique use case" instead of "custom integrations" :)

2023-03-29 22:55 UTC, shirgoldbird commented on developers/src/pages/documentation/guides/streaming-test-suite/index.mdx
> +First, make sure pyaudio and its portaudio dependency are installed, and you have a microphone connected to your computer. Then, run:
Added links!

2023-03-29 22:57 UTC, shirgoldbird commented on developers/src/pages/documentation/guides/streaming-test-suite/index.mdx
> +Now that you've validated you can stream WAV files and URLs to Deepgram, it's time to start the process of integrating your own audio. To do this, we'll start by taking a step back…and removing Deepg
I updated this heading to "Streaming Other Audio" and this sentence to:

"it's time to start the process of integrating other audio sources, so you can build something with Deepgram that's tailored to your business needs"

2023-03-29 23:27 UTC, shirgoldbird commented on developers/src/pages/documentation/guides/streaming-test-suite/index.mdx
> +The mock server exposes a similar interface to Deepgram's streaming service. It accepts websocket connections that specify an encoding, sample rate, and number of channels; and it expects a stream of
Added!

2023-03-30 00:04 UTC, shirgoldbird commented
@SandraRodgers believe I've addressed all comments! Please take a look and approve if all good :)

2023-03-31 22:07 UTC, SandraRodgers approved these changes

2023-03-31 22:07 UTC, merged