whisper guide
deepgram/web-next pull request #709
Opened 2023-04-11 19:33 UTC by SandraRodgers

2023-04-12 16:32 UTC, jpvajda commented on developers/src/pages/documentation/guides/deepgram-whisper/index.mdx
> +order: 1
Agreed, this might make a good place for the guide that tells user how to decide on which model to use in the future.

Nova has slightly different syntax for using Nova as it's following our future patterns of model=<tier>-<usecase>

So if we could a quick guide on that, it could be helpful. You'll see what I mean when I push up my Docs PR.

2023-04-12 16:37 UTC, jpvajda commented on developers/src/pages/documentation/guides/deepgram-whisper/index.mdx
> +In this guide, you’ll learn how to transcribe pre-recorded audio using Deepgram’s hosted Whisper API.
I take this back, I learned this AM:

the whisper model is not set to language auto detect, even though Open AI supports that, in our API we do not support this capability, though the 504 10 min time out is good to mention in a model guide.

2023-04-12 19:12 UTC, SandraRodgers commented on developers/src/pages/documentation/guides/deepgram-whisper/index.mdx
> +order: 1
In that case, I'll leave the navigation section as "Models" for now.

2023-04-12 19:32 UTC, SandraRodgers commented on developers/src/pages/documentation/guides/deepgram-whisper/index.mdx
> +- Scalable infrastructure that can handle high-traffic usage (up to 50 concurrent requests per minute).
@jpvajda Can you verify that the "50 concurrent requests per minute" is accurate?

2023-04-12 22:09 UTC, natalierutgers commented on developers/src/pages/documentation/guides/deepgram-whisper/index.mdx
> +- Scalable infrastructure that can handle high-traffic usage (up to 50 concurrent requests per minute).
It should be 50 requests per minute or 15 concurrent requests

2023-04-12 22:12 UTC, natalierutgers requested changes

2023-04-12 22:12 UTC, natalierutgers commented on developers/src/pages/documentation/guides/deepgram-whisper-cloud/index.mdx
> +  keywords: whisper, speech-to-text, speech to text, asr, openai, model, LLM, deepgram
Whisper isn't an LLM

2023-04-12 22:12 UTC, natalierutgers commented on developers/src/pages/documentation/guides/deepgram-whisper-cloud/index.mdx
> +<Alert type="info">Deepgram owns and maintains these Whisper models; they aren't hosted or run by Open AI.</Alert>
Let's swap "owns" for "hosts"

2023-04-12 22:27 UTC, jpvajda reviewed
made a few final tweaks.

2023-04-12 22:27 UTC, jpvajda commented on developers/src/pages/documentation/guides/deepgram-whisper-cloud/index.mdx
> +            ...
I'm seeing a red error in Github and `...` here, now sure what that is indicating.

2023-04-12 22:27 UTC, jpvajda commented on developers/src/pages/documentation/guides/deepgram-whisper-cloud/index.mdx
> +  keywords: whisper, speech-to-text, speech to text, asr, openai, model, LLM, deepgram
```suggestion
  keywords: whisper, speech-to-text, speech to text, asr, openai, model, deepgram
```

2023-04-12 22:27 UTC, jpvajda commented on developers/src/pages/documentation/guides/deepgram-whisper-cloud/index.mdx
> +<Alert type="info">Deepgram owns and maintains these Whisper models; they aren't hosted or run by Open AI.</Alert>
```suggestion
<Alert type="info">Deepgram hosts and maintains these Whisper models; they aren't hosted or run by Open AI.</Alert>
```

2023-04-12 22:29 UTC, SandraRodgers commented on developers/src/pages/documentation/guides/deepgram-whisper-cloud/index.mdx
> +            ...
It might not be happy with the '...' but it's standard to put that there when we don't include the full response

2023-04-12 23:44 UTC, jpvajda approved these changes

2023-04-13 00:17 UTC, natalierutgers approved these changes

2023-04-13 00:55 UTC, merged